# Generated by Django 6.0.6 on 2026-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "internal_length",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "internal_width",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "internal_height",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_weight_capacity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
                ("width", models.DecimalField(decimal_places=2, max_digits=10)),
                ("height", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
